// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = {
    throwsError: false,
    define: function(key, value) {
      if (this.hasOwnProperty(key)) {
        throw new Error("constant " + key + " already exists");
      }
      return Object.defineProperty(this, key, {
        get: function() {
          return value;
        },
        set: function() {
          if (this.throwsError) {
            throw new Error("accessing constant " + key);
          }
        }
      });
    }
  };

}).call(this);
